spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CAS-H-Y/config-server.git
server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
    register-with-eureka: true
